package hcl

import (
	"fmt"
	"sort"
	"strings"

	"github.com/tesserix/crossplane-validation/pkg/config"
	"github.com/tesserix/crossplane-validation/pkg/renderer"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// ConvertedSet holds HCL blocks ready for OpenTofu.
type ConvertedSet struct {
	// ProviderBlocks are the Terraform provider configurations.
	ProviderBlocks []Block
	// ResourceBlocks are the Terraform resource blocks.
	ResourceBlocks []Block
}

// Block represents a single HCL block (provider or resource).
type Block struct {
	Type       string
	Label      string
	Name       string
	Attributes map[string]interface{}
	SourceKey  string
	ImportID   string
}

// Convert transforms rendered Crossplane managed resources into HCL blocks.
func Convert(rs *renderer.RenderedSet, providers map[string]config.Provider) (*ConvertedSet, error) {
	cs := &ConvertedSet{}

	// Generate provider blocks from config
	for name, prov := range providers {
		pb := Block{
			Type:       "provider",
			Label:      mapProviderName(name),
			Name:       "default",
			Attributes: map[string]interface{}{},
		}
		if prov.Region != "" {
			pb.Attributes["region"] = prov.Region
		}
		if prov.Project != "" {
			pb.Attributes["project"] = prov.Project
		}
		if prov.SubscriptionID != "" {
			pb.Attributes["subscription_id"] = prov.SubscriptionID
		}
		cs.ProviderBlocks = append(cs.ProviderBlocks, pb)
	}

	// Convert each managed resource to an HCL resource block
	for _, r := range rs.Resources {
		block, err := convertResource(r, providers)
		if err != nil {
			continue
		}
		cs.ResourceBlocks = append(cs.ResourceBlocks, block)
	}

	return cs, nil
}

// ToHCL renders the converted set as HCL string.
func (cs *ConvertedSet) ToHCL() string {
	var sb strings.Builder

	sb.WriteString("# Auto-generated by crossplane-validate\n")
	sb.WriteString("# DO NOT EDIT — this is used for plan computation only\n\n")

	// Terraform block
	sb.WriteString("terraform {\n")
	sb.WriteString("  required_providers {\n")
	for _, pb := range cs.ProviderBlocks {
		source := providerSource(pb.Label)
		sb.WriteString(fmt.Sprintf("    %s = {\n", pb.Label))
		sb.WriteString(fmt.Sprintf("      source = %q\n", source))
		sb.WriteString("    }\n")
	}
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	// Provider blocks
	for _, pb := range cs.ProviderBlocks {
		sb.WriteString(fmt.Sprintf("provider %q {\n", pb.Label))
		writeAttributes(&sb, pb.Attributes, "  ")
		if pb.Label == "azurerm" {
			sb.WriteString("  features {}\n")
		}
		sb.WriteString("}\n\n")
	}

	// Resource blocks
	for _, rb := range cs.ResourceBlocks {
		sb.WriteString(fmt.Sprintf("resource %q %q {\n", rb.Label, rb.Name))
		writeAttributes(&sb, rb.Attributes, "  ")
		sb.WriteString("}\n\n")
	}

	return sb.String()
}

func convertResource(r renderer.RenderedResource, providers map[string]config.Provider) (Block, error) {
	res := r.Resource
	apiVersion := res.GetAPIVersion()
	kind := res.GetKind()
	name := sanitizeName(res.GetName())

	tfType, err := mapResourceType(apiVersion, kind)
	if err != nil {
		return Block{}, err
	}

	attrs := extractForProvider(res)

	// Terraform requires a 'name' attribute for most resources
	if _, hasName := attrs["name"]; !hasName {
		attrs["name"] = res.GetName()
	}

	importID := buildImportID(tfType, attrs, providers)

	return Block{
		Type:       "resource",
		Label:      tfType,
		Name:       name,
		Attributes: attrs,
		SourceKey:  r.ResourceKey(),
		ImportID:   importID,
	}, nil
}

// mapResourceType maps a Crossplane API version + kind to a Terraform resource type.
// This leverages the 1:1 mapping that exists because Upjet generates Crossplane
// providers from Terraform providers.
func mapResourceType(apiVersion, kind string) (string, error) {
	// Upbound provider-aws mappings
	awsMappings := map[string]map[string]string{
		"s3.aws.upbound.io": {
			"Bucket":          "aws_s3_bucket",
			"BucketPolicy":    "aws_s3_bucket_policy",
			"BucketACL":       "aws_s3_bucket_acl",
			"BucketVersioning": "aws_s3_bucket_versioning",
		},
		"iam.aws.upbound.io": {
			"Role":             "aws_iam_role",
			"RolePolicy":       "aws_iam_role_policy",
			"RolePolicyAttachment": "aws_iam_role_policy_attachment",
			"Policy":           "aws_iam_policy",
			"User":             "aws_iam_user",
			"Group":            "aws_iam_group",
		},
		"ec2.aws.upbound.io": {
			"VPC":              "aws_vpc",
			"Subnet":           "aws_subnet",
			"SecurityGroup":    "aws_security_group",
			"Instance":         "aws_instance",
			"InternetGateway":  "aws_internet_gateway",
			"RouteTable":       "aws_route_table",
			"NATGateway":       "aws_nat_gateway",
			"EIP":              "aws_eip",
		},
		"rds.aws.upbound.io": {
			"Instance":         "aws_db_instance",
			"Cluster":          "aws_rds_cluster",
			"SubnetGroup":      "aws_db_subnet_group",
		},
		"eks.aws.upbound.io": {
			"Cluster":          "aws_eks_cluster",
			"NodeGroup":        "aws_eks_node_group",
		},
	}

	// Upbound provider-gcp mappings
	gcpMappings := map[string]map[string]string{
		"storage.gcp.upbound.io": {
			"Bucket": "google_storage_bucket",
		},
		"compute.gcp.upbound.io": {
			"Instance":  "google_compute_instance",
			"Network":   "google_compute_network",
			"Subnetwork": "google_compute_subnetwork",
			"Firewall":  "google_compute_firewall",
		},
		"container.gcp.upbound.io": {
			"Cluster":  "google_container_cluster",
			"NodePool": "google_container_node_pool",
		},
		"sql.gcp.upbound.io": {
			"DatabaseInstance": "google_sql_database_instance",
			"Database":         "google_sql_database",
			"User":             "google_sql_user",
		},
		"iam.gcp.upbound.io": {
			"ServiceAccount": "google_service_account",
		},
	}

	// Azure mappings
	azureMappings := map[string]map[string]string{
		"azure.upbound.io": {
			"ResourceGroup": "azurerm_resource_group",
		},
		"storage.azure.upbound.io": {
			"Account":   "azurerm_storage_account",
			"Container": "azurerm_storage_container",
		},
		"network.azure.upbound.io": {
			"VirtualNetwork": "azurerm_virtual_network",
			"Subnet":         "azurerm_subnet",
		},
		"compute.azure.upbound.io": {
			"LinuxVirtualMachine": "azurerm_linux_virtual_machine",
		},
	}

	group := extractAPIGroup(apiVersion)

	// Search in order: AWS, GCP, Azure
	for prefix, kinds := range awsMappings {
		if strings.HasPrefix(group, prefix) {
			if tfType, ok := kinds[kind]; ok {
				return tfType, nil
			}
		}
	}
	for prefix, kinds := range gcpMappings {
		if strings.HasPrefix(group, prefix) {
			if tfType, ok := kinds[kind]; ok {
				return tfType, nil
			}
		}
	}
	for prefix, kinds := range azureMappings {
		if strings.HasPrefix(group, prefix) {
			if tfType, ok := kinds[kind]; ok {
				return tfType, nil
			}
		}
	}

	// Fallback: generate a best-guess name
	return guessTerraformType(group, kind), nil
}

func extractForProvider(res unstructured.Unstructured) map[string]interface{} {
	fp, found, _ := unstructured.NestedMap(res.Object, "spec", "forProvider")
	if found {
		return flattenForTerraform(fp)
	}

	// Fallback to spec
	spec, found, _ := unstructured.NestedMap(res.Object, "spec")
	if found {
		// Remove Crossplane-specific fields
		delete(spec, "providerConfigRef")
		delete(spec, "publishConnectionDetailsTo")
		delete(spec, "writeConnectionSecretToRef")
		delete(spec, "compositionRef")
		delete(spec, "compositionSelector")
		delete(spec, "managementPolicies")
		delete(spec, "deletionPolicy")
		return flattenForTerraform(spec)
	}

	return map[string]interface{}{}
}

// flattenForTerraform converts Crossplane field naming to Terraform conventions.
func flattenForTerraform(m map[string]interface{}) map[string]interface{} {
	result := make(map[string]interface{}, len(m))
	for k, v := range m {
		// Convert camelCase to snake_case for Terraform
		tfKey := camelToSnake(k)

		// Skip Crossplane-specific reference fields
		if strings.HasSuffix(k, "Ref") || strings.HasSuffix(k, "Refs") ||
			strings.HasSuffix(k, "Selector") {
			continue
		}

		switch val := v.(type) {
		case map[string]interface{}:
			result[tfKey] = flattenForTerraform(val)
		default:
			result[tfKey] = val
		}
	}
	return result
}

func camelToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteRune('_')
			}
			result.WriteRune(r + 32) // toLower
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func sanitizeName(name string) string {
	return strings.ReplaceAll(strings.ReplaceAll(name, "-", "_"), ".", "_")
}

func extractAPIGroup(apiVersion string) string {
	parts := strings.Split(apiVersion, "/")
	if len(parts) > 0 {
		return parts[0]
	}
	return apiVersion
}

func mapProviderName(name string) string {
	switch strings.ToLower(name) {
	case "aws":
		return "aws"
	case "gcp":
		return "google"
	case "azure":
		return "azurerm"
	default:
		return name
	}
}

func providerSource(name string) string {
	switch name {
	case "aws":
		return "hashicorp/aws"
	case "google":
		return "hashicorp/google"
	case "azurerm":
		return "hashicorp/azurerm"
	default:
		return "hashicorp/" + name
	}
}

func buildImportID(tfType string, attrs map[string]interface{}, providers map[string]config.Provider) string {
	subscriptionID := ""
	for name, prov := range providers {
		if strings.ToLower(name) == "azure" && prov.SubscriptionID != "" {
			subscriptionID = prov.SubscriptionID
		}
	}

	rg, _ := attrs["resource_group_name"].(string)
	name, _ := attrs["name"].(string)

	switch tfType {
	case "azurerm_storage_account":
		if subscriptionID != "" && rg != "" && name != "" {
			return fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Storage/storageAccounts/%s",
				subscriptionID, rg, name)
		}
	case "azurerm_resource_group":
		if subscriptionID != "" && name != "" {
			return fmt.Sprintf("/subscriptions/%s/resourceGroups/%s", subscriptionID, name)
		}
	case "azurerm_virtual_network":
		if subscriptionID != "" && rg != "" && name != "" {
			return fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/virtualNetworks/%s",
				subscriptionID, rg, name)
		}
	case "azurerm_subnet":
		vnet, _ := attrs["virtual_network_name"].(string)
		if subscriptionID != "" && rg != "" && vnet != "" && name != "" {
			return fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/virtualNetworks/%s/subnets/%s",
				subscriptionID, rg, vnet, name)
		}
	}

	// AWS resources use name/id directly
	if strings.HasPrefix(tfType, "aws_") {
		if name != "" {
			return name
		}
	}

	return ""
}

func guessTerraformType(group, kind string) string {
	// Best-effort: extract provider prefix from group and combine with snake_case kind
	provider := "unknown"
	if strings.Contains(group, "aws") {
		provider = "aws"
	} else if strings.Contains(group, "gcp") {
		provider = "google"
	} else if strings.Contains(group, "azure") {
		provider = "azurerm"
	}
	return provider + "_" + camelToSnake(kind)
}

var mapStyleFields = map[string]bool{
	"tags": true, "labels": true, "annotations": true, "environment": true,
}

func writeAttributes(sb *strings.Builder, attrs map[string]interface{}, indent string) {
	keys := sortedKeys(attrs)
	for _, k := range keys {
		v := attrs[k]
		switch val := v.(type) {
		case map[string]interface{}:
			if mapStyleFields[k] {
				sb.WriteString(fmt.Sprintf("%s%s = {\n", indent, k))
				innerKeys := sortedKeys(val)
				for _, ik := range innerKeys {
					sb.WriteString(fmt.Sprintf("%s  %s = %q\n", indent, ik, fmt.Sprintf("%v", val[ik])))
				}
				sb.WriteString(fmt.Sprintf("%s}\n", indent))
			} else {
				sb.WriteString(fmt.Sprintf("%s%s {\n", indent, k))
				writeAttributes(sb, val, indent+"  ")
				sb.WriteString(fmt.Sprintf("%s}\n", indent))
			}
		case string:
			sb.WriteString(fmt.Sprintf("%s%s = %q\n", indent, k, val))
		case bool:
			sb.WriteString(fmt.Sprintf("%s%s = %v\n", indent, k, val))
		default:
			sb.WriteString(fmt.Sprintf("%s%s = %q\n", indent, k, fmt.Sprintf("%v", val)))
		}
	}
}

func sortedKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
