apiVersion: v1
kind: Service
metadata:
  name: crossplane-validate-operator
  labels:
    app.kubernetes.io/name: crossplane-validate-operator
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9443
      targetPort: grpc
    - name: health
      port: 8081
      targetPort: health
  selector:
    app.kubernetes.io/name: crossplane-validate-operator
