apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
